name: Build and Push Frontend Docker Image to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker image name
        id: image
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/spotifai-frontend:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

