name: Build and Push Frontend Docker Image to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker image name
        id: image
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/spotifai-frontend:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: spotifai-frontend
          image: docker.io/${{ env.IMAGE_NAME }}
          region: europe-west1

